In [2]:
#Numpy

In [3]:
import numpy as np

In [4]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [5]:
arr1.shape

(5,)

In [6]:
arr1.size

5

In [32]:
arr1.itemsize

8

In [8]:
#Indexing
arr1[0]

np.int64(40)

In [9]:
arr1[3]

np.int64(40)

In [10]:
arr1[-2]

np.int64(40)

In [11]:
#Slicing
arr1[2:4]

array([30, 40])

In [13]:
arr1[::-1]

array([50, 40, 30, 20, 10])

In [37]:
#Memory Checking

In [17]:
import numpy as np
import time
import sys

In [15]:
r1=range(100)
print(*r1)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99


In [19]:
sys.getsizeof(1)

28

In [20]:
#Memory allocated
28*100

2800

In [21]:
L1=[100,200,300,400,500]
L1

[100, 200, 300, 400, 500]

In [33]:
#Memory of list
print(sys.getsizeof(100)*len(L1))

140


In [22]:
sys.getsizeof(100)

28

In [23]:
#Memory allocated
28*5

140

In [25]:
r2=np.arange(100)
r2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
r2.itemsize

8

In [27]:
print(r2.size*r2.itemsize)

800


In [30]:
arr2=np.array([100,200,300,400,500])

In [31]:
arr2.itemsize

8

In [35]:
#Memory of array
5*8

40

In [36]:
#Memory of list is 140
#Memory of array is 40

In [38]:
#Time Checking

In [39]:
L1=range(100)
L2=range(100)

In [40]:
ar1=np.arange(100)
ar2=np.arange(100)

In [45]:
startTime=time.time()
startTime

1763620818.1781194

In [46]:
size=1000000

In [49]:
courses=['python','pandas','numpy','matplotlib']
fee=[10000,5000,4500,3000]

In [52]:
for i,j in zip(courses,fee):
    print(courses, fee)

['python', 'pandas', 'numpy', 'matplotlib'] [10000, 5000, 4500, 3000]
['python', 'pandas', 'numpy', 'matplotlib'] [10000, 5000, 4500, 3000]
['python', 'pandas', 'numpy', 'matplotlib'] [10000, 5000, 4500, 3000]
['python', 'pandas', 'numpy', 'matplotlib'] [10000, 5000, 4500, 3000]
