In [2]:
#Numpy

In [3]:
import numpy as np

In [4]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [5]:
arr1.shape

(5,)

In [6]:
arr1.size

5

In [32]:
arr1.itemsize

8

In [8]:
#Indexing
arr1[0]

np.int64(40)

In [9]:
arr1[3]

np.int64(40)

In [10]:
arr1[-2]

np.int64(40)

In [11]:
#Slicing
arr1[2:4]

array([30, 40])

In [13]:
arr1[::-1]

array([50, 40, 30, 20, 10])

In [37]:
#Memory Checking

In [17]:
import numpy as np
import time
import sys

In [15]:
r1=range(100)
print(*r1)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99


In [19]:
sys.getsizeof(1)

28

In [20]:
#Memory allocated
28*100

2800

In [21]:
L1=[100,200,300,400,500]
L1

[100, 200, 300, 400, 500]

In [33]:
#Memory of list
print(sys.getsizeof(100)*len(L1))

140


In [22]:
sys.getsizeof(100)

28

In [23]:
#Memory allocated
28*5

140

In [25]:
r2=np.arange(100)
r2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
r2.itemsize

8

In [27]:
print(r2.size*r2.itemsize)

800


In [30]:
arr2=np.array([100,200,300,400,500])

In [31]:
arr2.itemsize

8

In [35]:
#Memory of array
5*8

40

In [36]:
#Memory of list is 140
#Memory of array is 40

In [38]:
#Time Checking

In [45]:
startTime=time.time()
startTime

1763620818.1781194

In [46]:
size=1000000

In [53]:
courses=['python','pandas','numpy','matplotlib']
fee=[10000,5000,4500,3000]

In [55]:
for courses,fee in zip(courses,fee):
    print(courses, fee)

python 10000
pandas 5000
numpy 4500
matplotlib 3000


In [63]:
list1=[1,2,3,4,5]
list2=[1,2,3,4,5]
list1+list2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [65]:
[(a+b) for a,b in zip(list1,list2)]

[2, 4, 6, 8, 10]

In [64]:
array1=np.array([1,2,3,4,5])
array2=np.array([1,2,3,4,5])
array1+array2

array([ 2,  4,  6,  8, 10])

In [59]:
r1=range(size)
r2=range(size)
startTime=time.time()
test1=[(a+b) for a,b in zip(r1,r2)]
print('Time taken for List', (time.time()-startTime)*1000)

Time taken for List 299.9615669250488


In [61]:
arr3=np.arange(size)
arr4=np.arange(size)
startTime=time.time()
test2=arr3+arr4
print('Time taken for Arrays', (time.time()-startTime)*1000)

Time taken for Arrays 5.995273590087891


In [66]:
#1D array
array_1=np.array([1,2,3,4,5])
array_1

array([1, 2, 3, 4, 5])

In [67]:
array_1.size

5

In [68]:
array_1.shape

(5,)

In [69]:
array_1.itemsize

8

In [70]:
array_1[0]

np.int64(1)

In [77]:
array_1.dtype

dtype('int64')

In [79]:
array_1.ndim

1

In [72]:
#2D array
array_2=np.array([[1,2],[3,4],[5,6]])
array_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
array_2.size

6

In [74]:
array_2.shape

(3, 2)

In [90]:
array_2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
array_2.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [94]:
array_2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [75]:
array_2.itemsize

8

In [76]:
array_2[0]

array([1, 2])

In [78]:
array_2.dtype

dtype('int64')

In [80]:
array_2.ndim

2

In [81]:
array_3=np.array([[1,2],[3,4],[5,6]],dtype=complex)
array_3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [83]:
array_4=np.zeros((3,4))
array_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
array_5=np.ones((3,4))
array_5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [87]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [89]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [95]:
array_6=np.array([[1,2],[3,4],[5,6]])
array_6

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
array_6.ravel()

array([1, 2, 3, 4, 5, 6])

In [97]:
array_6.min()

np.int64(1)

In [98]:
array_6.max()

np.int64(6)

In [99]:
array_6.sum()

np.int64(21)

In [100]:
array_6.mean()

np.float64(3.5)

In [101]:
array_6.std()

np.float64(1.707825127659933)

In [103]:
array_6.strides

(16, 8)

In [104]:
array_6.size

6

In [105]:
array_6.sum(axis=0)

array([ 9, 12])

In [106]:
array_6.sum(axis=1)

array([ 3,  7, 11])

In [107]:
ar1=np.array([[1,2],[3,4]])
ar1

array([[1, 2],
       [3, 4]])

In [108]:
ar2=np.array([[5,6],[7,8]])
ar2

array([[5, 6],
       [7, 8]])

In [109]:
ar1+ar2

array([[ 6,  8],
       [10, 12]])

In [110]:
ar1*ar2

array([[ 5, 12],
       [21, 32]])

In [111]:
ar1/ar2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [112]:
ar2/ar1

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [113]:
ar1.dot(ar2)

array([[19, 22],
       [43, 50]])

In [115]:
ar1@ar2 #Symbolic of dot product

array([[19, 22],
       [43, 50]])

In [116]:
#Indexing and Slicing
array1=np.array([n for n in range(1,11)])
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
array1[4]

np.int64(5)

In [118]:
array1[4:8]

array([5, 6, 7, 8])

In [119]:
array1[-1]

np.int64(10)

In [120]:
array1[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
array1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])