In [2]:
#Numpy

In [3]:
import numpy as np

In [4]:
arr1=np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [5]:
arr1.shape

(5,)

In [6]:
arr1.size

5

In [8]:
#Indexing
arr1[0]

np.int64(40)

In [9]:
arr1[3]

np.int64(40)

In [10]:
arr1[-2]

np.int64(40)

In [11]:
#Slicing
arr1[2:4]

array([30, 40])

In [13]:
arr1[::-1]

array([50, 40, 30, 20, 10])

In [ ]:
#We can do all above with lists too
#List VS Numpy array
    Array is faster than list
    Array will take less memo